Build desktop features
Armynerh/personal_portfolio pull request #8
Opened 2023-06-15 12:34 UTC by Armynerh

make changes to portfolio for responsiveness on large devices
add new images
change style.css to pass linters
change index.html to include desktop images

2023-06-15 14:35 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @Armynerh :wave:  
You've done a nice job so far on the desktop view of your portfolio project :clap: :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close](https://github.com/Armynerh/personal_portfolio/assets/93520178/da0630b6-32fa-46ef-bd2a-ad864b1419c7)

## Highlights
- [x] Use of media queries :heavy_check_mark: 
- [x] Use of both `Flexbox` and `Grid` :heavy_check_mark: 

## Required Changes ♻️
Starting with your README: 
- [ ] Kindly replace [your project name] with the name of your project
![Screenshot from 2023-06-15 14-51-44](https://github.com/Armynerh/personal_portfolio/assets/93520178/4d2048b3-7ee3-446b-82e2-165322b967fc)
- [ ] Kindly remove the description of the `Live Demo Link` section:
![Screenshot from 2023-06-15 14-53-03](https://github.com/Armynerh/personal_portfolio/assets/93520178/0c622eb1-c18e-4994-ac6a-6ba02b4a6589)

Moving on to the portfolio: 
- [ ] If you check the figma template, you'll see that there's a button with a down arrow under the social media icons, you should add it to stick as much as possible to the design.
![Screenshot from 2023-06-15 14-56-41](https://github.com/Armynerh/personal_portfolio/assets/93520178/02bd07e5-7f9d-4b1e-8fc5-c4e481983da2)

- [ ] In the mobile view, the skills cards are not perfectly centered, there's more space on the right than on the left: 
![Screenshot from 2023-06-15 15-22-57](https://github.com/Armynerh/personal_portfolio/assets/93520178/a4db6401-a515-4dc7-9ff2-6c62e75df42b)

- [ ] In the desktop view, if you check the figma template, the background image should start at the top of the page, not at the start of the hero section: 
    - The template: 
    ![Screenshot from 2023-06-15 15-08-36](https://github.com/Armynerh/personal_portfolio/assets/93520178/79641f0b-e380-44aa-973a-677cd1fa46f9)
    - Your design: 
    ![Screenshot from 2023-06-15 15-08-52](https://github.com/Armynerh/personal_portfolio/assets/93520178/6f70197e-8034-42a5-a456-1c609017a192)

- [x] In the desktop view, if you check the figma template, there should be more spacing on the left and right of the following sections: `My recent works`, `About me`, `Contact me`
    - The template: 
    ![Template 3-main](https://github.com/Armynerh/personal_portfolio/assets/93520178/98374603-694e-473f-914d-010486ffc4f0)

- [ ] In the desktop view, if you check the figma template, you'll see that the footer which holds the social media icons sticks at the bottom of the page with a top border: 
    - The template: 
    ![Screenshot from 2023-06-15 15-25-53](https://github.com/Armynerh/personal_portfolio/assets/93520178/af47f916-8f90-4b06-b076-a22a0fb45501)
    - Your design: 
    ![Screenshot from 2023-06-15 15-26-22](https://github.com/Armynerh/personal_portfolio/assets/93520178/a80fa4c9-bf48-4ebc-a486-887174639b9f)

_Check the comments under the review :point_down: _

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and :computer: Happy coding! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 18:27 UTC, osamaashraf6 requested changes
Hi @Armynerh 😊, 

Good job so far!
There are some issues that you still need to work on from the previous reviewer to go to the next project but you are almost there!
![SoCloseAlmostGIF (3)](https://github.com/Armynerh/personal_portfolio/assets/83360636/10552930-1786-4d33-84f0-5c8e981bc577)

## Highlights🎉🎉

- [ ] Following Figma design😊👌
- [ ] Use the semantics elements💯
- [ ] Nice design .🚀
- [ ] Use the flexbox to place the items 😃👍

## Required Changes ♻️

- [ ] Kindly 😃 as stated by the previous reviewer, Kindly replace [your project name] with the name of your project to make the Readme professional💯

| Your Readme| 
| --- |  
|  ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/2f122139-c8a7-4061-91b3-bb35ae7c4687) |

- [ ] Kindly 😃 as stated by the previous reviewer, Kindly remove the description of the Live Demo Link section to make the Readme professional🚀

| Your Readme| 
| --- |  
|  ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/dc81c5e8-5801-4e92-b725-6354ef36d3d5) |

_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 18:27 UTC, osamaashraf6 commented on index.html
> +                </div>
- [ ] Kindly 😃 as stated by the previous reviewer, If you check the Figma template, you'll see that there's a button with a down arrow under the social media icons,  so please I suggest adding it to stick as much as possible to the design.💯🚀

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
| ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/37d4f2a1-5efb-4600-b3c6-a2e860e981e8)    |     ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/a5adb9a9-cc32-4092-a981-600350d30b4c)  |

2023-06-15 18:27 UTC, osamaashraf6 commented on index.html
> +        </footer>
- [x] Kindly 😃 as stated by the previous reviewer, In the desktop view, if you check the Figma template, you'll see that the footer which holds the social media icons sticks at the bottom of the page with a top border, so please try to make that to make the design nice like the original💯🚀

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/5893dee5-a0d2-4bd9-a542-c7ca7e206d1c)   |     ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/6cee6f85-cf0b-4823-805e-ecefc898b1ec) |

2023-06-15 18:27 UTC, osamaashraf6 commented on style.css
> +    background-size: cover;
- [x] You did a great job 😃at implementing the most changes from the previous reviewer. however I see that the previous reviewer told you to put the background image at the top of the page, not the section and you did a great effort to put it, but as stated by the previous reviewer please try to stick to the Figma Design and move the background image little to up to make it nice like the Figma design 💯🚀

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|   ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/91ad9a74-ca13-4941-9763-f8607d6152b8)  |    ![image](https://github.com/Armynerh/personal_portfolio/assets/83360636/d3e800f4-f523-4b51-88f3-d38380641421)   |

2023-06-15 20:01 UTC, emmiiorji requested changes
Hi @Armynerh, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220869680-787a77f7-922b-4e57-8fa4-368533d83b89.gif'/>
</div>

## Good Highlights✔️

- You have implemented most of the required changes


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 20:01 UTC, emmiiorji commented on style.css
> +    background-size: cover;
> * [ ]  You did a great job 😃at implementing the most changes from the previous reviewer. however I see that the previous reviewer told you to put the background image at the top of the page, not the section and you did a great effort to put it, but as stated by the previous reviewer please try to stick to the Figma Design and move the background image little to up to make it nice like the Figma design 💯🚀
> 
> > Check below to see the difference 😊⤵️
> > If you can not see the image clearly just click on it to open a new tab in the browser😊
> 
> Original design	Your design
> ![image](https://user-images.githubusercontent.com/83360636/246204101-91ad9a74-ca13-4941-9763-f8607d6152b8.png)	![image](https://user-images.githubusercontent.com/83360636/246204057-d3e800f4-f523-4b51-88f3-d38380641421.png)

While trying to implement the previous reviewer's suggestion, you seem to have introduced another issue where the navigation items are fixed.
Kindly close up the white space as highlighted below and make the items not to be fixed.

Your design:
![image](https://github.com/Armynerh/personal_portfolio/assets/20554583/5d19d522-9975-4e1c-baa8-e3d282689e83) ![image](https://github.com/Armynerh/personal_portfolio/assets/20554583/92289c5b-1e5c-43ea-bb15-9f59443a555d)

Figma design:
![image](https://github.com/Armynerh/personal_portfolio/assets/20554583/0c427434-8695-4011-95c8-df98e45075d6)

2023-06-16 01:22 UTC, Strangeal approved these changes
Hi @Armynerh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 02:14 UTC, merged